version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Angelina

  web:
    build: ~/fa-practicum-1/djangoProject
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://root:mypassword@db:5432/django
    depends_on:
      - db

volumes:
  postgres_data: