# Generated by Django 5.0.2 on 2024-03-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_en_EN',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_ru_RU',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_EN',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru_RU',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
